title: "Let's Do Thy Math"
email: letsdothymath@gmail.com
timezone: UTC
baseurl: "/lets-do-thy-math"
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo_favicon.ico'
author: Thy
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
# ganalytics: UA-113961478-1

# Authors
authors:
  thy:
    name: Thy
    display_name: Thy
    #avatar: 'assets/images/sal.png'
    email: letsdothymath@gmail.com
    #web: https://www.wowthemes.net/category/jekyll-themes/
    #twitter: https://twitter.com/wowthemesnet
    description: "Author of the website's content"  
# Social
social:
  youtube: https://www.youtube.com/@LetsDoThyMath
  tiktok: https://www.tiktok.com/@letsdothymath
  instagram: https://www.instagram.com/letsdothymath/
  #facebook: https://www.facebook.com/bootstrapstartercom-346329609045284
  #twitter: https://twitter.com/bstartercom

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives